[rlbot]
launcher = "steam"
# We'll run the bot ourself so we don't have restart the match
# `python src/bot.py` in our case
auto_start_bots = false

[match]
enable_rendering = true

[mutators]
match_length = "Unlimited"

[[cars]]
config_file = "src/bot.toml"
team = 0
